server:
  port: 8888
spring:
  application:
    name: systempro-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fernandolilo/profile-microservice-testes
          # username: username => para o caso de repositorio privado
          # password: password=> tambem para repositorio privado
          default-label: master
          search-paths:
          - 'greeting-service*'